// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// backoskt_nr_cpp
List backoskt_nr_cpp(NumericVector Z, double X_mean, double X_sd, double g, double h, double tol, int maxiter);
RcppExport SEXP _osktnorm_backoskt_nr_cpp(SEXP ZSEXP, SEXP X_meanSEXP, SEXP X_sdSEXP, SEXP gSEXP, SEXP hSEXP, SEXP tolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< double >::type X_mean(X_meanSEXP);
    Rcpp::traits::input_parameter< double >::type X_sd(X_sdSEXP);
    Rcpp::traits::input_parameter< double >::type g(gSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(backoskt_nr_cpp(Z, X_mean, X_sd, g, h, tol, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// backoskt_uniroot_cpp
List backoskt_uniroot_cpp(NumericVector Z, double X_mean, double X_sd, double g, double h, double tol, int maxiter);
RcppExport SEXP _osktnorm_backoskt_uniroot_cpp(SEXP ZSEXP, SEXP X_meanSEXP, SEXP X_sdSEXP, SEXP gSEXP, SEXP hSEXP, SEXP tolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< double >::type X_mean(X_meanSEXP);
    Rcpp::traits::input_parameter< double >::type X_sd(X_sdSEXP);
    Rcpp::traits::input_parameter< double >::type g(gSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(backoskt_uniroot_cpp(Z, X_mean, X_sd, g, h, tol, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// backoskt_auto_cpp
List backoskt_auto_cpp(NumericVector Z, double X_mean, double X_sd, double g, double h, double tol, int maxiter_nr, int maxiter_brent);
RcppExport SEXP _osktnorm_backoskt_auto_cpp(SEXP ZSEXP, SEXP X_meanSEXP, SEXP X_sdSEXP, SEXP gSEXP, SEXP hSEXP, SEXP tolSEXP, SEXP maxiter_nrSEXP, SEXP maxiter_brentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< double >::type X_mean(X_meanSEXP);
    Rcpp::traits::input_parameter< double >::type X_sd(X_sdSEXP);
    Rcpp::traits::input_parameter< double >::type g(gSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter_nr(maxiter_nrSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter_brent(maxiter_brentSEXP);
    rcpp_result_gen = Rcpp::wrap(backoskt_auto_cpp(Z, X_mean, X_sd, g, h, tol, maxiter_nr, maxiter_brent));
    return rcpp_result_gen;
END_RCPP
}
// osktfast_cpp
List osktfast_cpp(std::vector<double> x, double g0, double h0, double gmin, double gmax, double hmin, double hmax, int maxiter);
RcppExport SEXP _osktnorm_osktfast_cpp(SEXP xSEXP, SEXP g0SEXP, SEXP h0SEXP, SEXP gminSEXP, SEXP gmaxSEXP, SEXP hminSEXP, SEXP hmaxSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type g0(g0SEXP);
    Rcpp::traits::input_parameter< double >::type h0(h0SEXP);
    Rcpp::traits::input_parameter< double >::type gmin(gminSEXP);
    Rcpp::traits::input_parameter< double >::type gmax(gmaxSEXP);
    Rcpp::traits::input_parameter< double >::type hmin(hminSEXP);
    Rcpp::traits::input_parameter< double >::type hmax(hmaxSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(osktfast_cpp(x, g0, h0, gmin, gmax, hmin, hmax, maxiter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_osktnorm_backoskt_nr_cpp", (DL_FUNC) &_osktnorm_backoskt_nr_cpp, 7},
    {"_osktnorm_backoskt_uniroot_cpp", (DL_FUNC) &_osktnorm_backoskt_uniroot_cpp, 7},
    {"_osktnorm_backoskt_auto_cpp", (DL_FUNC) &_osktnorm_backoskt_auto_cpp, 8},
    {"_osktnorm_osktfast_cpp", (DL_FUNC) &_osktnorm_osktfast_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_osktnorm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
