# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

backoskt_nr_cpp <- function(Z, X_mean, X_sd, g, h, tol = 1e-10, maxiter = 1000L) {
    .Call(`_osktnorm_backoskt_nr_cpp`, Z, X_mean, X_sd, g, h, tol, maxiter)
}

backoskt_uniroot_cpp <- function(Z, X_mean, X_sd, g, h, tol = 1e-10, maxiter = 2000L) {
    .Call(`_osktnorm_backoskt_uniroot_cpp`, Z, X_mean, X_sd, g, h, tol, maxiter)
}

backoskt_auto_cpp <- function(Z, X_mean, X_sd, g, h, tol = 1e-10, maxiter_nr = 1000L, maxiter_brent = 2000L) {
    .Call(`_osktnorm_backoskt_auto_cpp`, Z, X_mean, X_sd, g, h, tol, maxiter_nr, maxiter_brent)
}

osktfast_cpp <- function(x, g0 = 0.1, h0 = 0.1, gmin = -1.0, gmax = 1.0, hmin = 0.0, hmax = 0.5, maxiter = 200L) {
    .Call(`_osktnorm_osktfast_cpp`, x, g0, h0, gmin, gmax, hmin, hmax, maxiter)
}

